all: \
	iso/music/getup/getup.mus \
	iso/music/copy/copy.mus \
	iso/music/phase1/phase1battle.mus \
	iso/music/phase1/phase1.mus \
	iso/music/phase2/phase2.mus \

iso/%.mus: iso/%.txt
	tools/funkinmuspak/funkinmuspak $@ $<
